import type { Customer, Vehicle, Appointment, AutoPart, StaffMember, Certification, StaffCertification } from "@/src/types"

export const mockCustomers: Customer[] = [
  {
    id: "cus_1",
    customerName: "John Doe",
    email: "john.doe@example.com",
    phone: "+1 (555) 123-4567",
    address: "123 Main St, San Francisco, CA 94102",
    vehicleCount: 2,
    registeredDate: "2023-01-15",
  },
  {
    id: "cus_2",
    customerName: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1 (555) 234-5678",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    vehicleCount: 1,
    registeredDate: "2023-02-20",
  },
  {
    id: "cus_3",
    customerName: "Michael Johnson",
    email: "michael.j@example.com",
    phone: "+1 (555) 345-6789",
    address: "789 Pine Rd, San Diego, CA 92101",
    vehicleCount: 3,
    registeredDate: "2023-03-10",
  },
  {
    id: "cus_4",
    customerName: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "+1 (555) 456-7890",
    address: "321 Elm St, Sacramento, CA 95814",
    vehicleCount: 1,
    registeredDate: "2023-04-05",
  },
  {
    id: "cus_5",
    customerName: "Robert Wilson",
    email: "robert.w@example.com",
    phone: "+1 (555) 567-8901",
    address: "654 Maple Dr, San Jose, CA 95110",
    vehicleCount: 2,
    registeredDate: "2023-05-12",
  },
  {
    id: "cus_6",
    customerName: "Sarah Brown",
    email: "sarah.brown@example.com",
    phone: "+1 (555) 678-9012",
    address: "987 Cedar Ln, Oakland, CA 94601",
    vehicleCount: 1,
    registeredDate: "2023-06-18",
  },
  {
    id: "cus_7",
    customerName: "David Martinez",
    email: "david.m@example.com",
    phone: "+1 (555) 789-0123",
    address: "147 Birch Ct, Fresno, CA 93650",
    vehicleCount: 2,
    registeredDate: "2023-07-22",
  },
  {
    id: "cus_8",
    customerName: "Lisa Anderson",
    email: "lisa.anderson@example.com",
    phone: "+1 (555) 890-1234",
    address: "258 Spruce Way, Long Beach, CA 90802",
    vehicleCount: 1,
    registeredDate: "2023-08-30",
  },
  {
    id: "cus_9",
    customerName: "James Taylor",
    email: "james.taylor@example.com",
    phone: "+1 (555) 901-2345",
    address: "369 Willow Blvd, Bakersfield, CA 93301",
    vehicleCount: 3,
    registeredDate: "2023-09-14",
  },
  {
    id: "cus_10",
    customerName: "Jennifer Thomas",
    email: "jennifer.t@example.com",
    phone: "+1 (555) 012-3456",
    address: "741 Ash St, Anaheim, CA 92801",
    vehicleCount: 1,
    registeredDate: "2023-10-08",
  },
  {
    id: "cus_11",
    customerName: "Christopher Lee",
    email: "chris.lee@example.com",
    phone: "+1 (555) 123-7890",
    address: "852 Poplar Ave, Santa Ana, CA 92701",
    vehicleCount: 2,
    registeredDate: "2023-11-20",
  },
  {
    id: "cus_12",
    customerName: "Amanda White",
    email: "amanda.white@example.com",
    phone: "+1 (555) 234-8901",
    address: "963 Hickory Rd, Riverside, CA 92501",
    vehicleCount: 1,
    registeredDate: "2023-12-05",
  },
  {
    id: "cus_13",
    customerName: "Daniel Harris",
    email: "daniel.harris@example.com",
    phone: "+1 (555) 345-9012",
    address: "159 Walnut Dr, Stockton, CA 95202",
    vehicleCount: 2,
    registeredDate: "2024-01-17",
  },
  {
    id: "cus_14",
    customerName: "Michelle Clark",
    email: "michelle.c@example.com",
    phone: "+1 (555) 456-0123",
    address: "357 Chestnut Ln, Irvine, CA 92602",
    vehicleCount: 1,
    registeredDate: "2024-02-28",
  },
  {
    id: "cus_15",
    customerName: "Kevin Rodriguez",
    email: "kevin.r@example.com",
    phone: "+1 (555) 567-1234",
    address: "486 Sycamore Ct, Fremont, CA 94536",
    vehicleCount: 3,
    registeredDate: "2024-03-15",
  },
]

export const mockVehicles: Vehicle[] = [
  {
    id: "veh_1",
    customerId: "cus_1",
    customerName: "John Doe",
    vehicleName: "Tesla Model 3",
    model: "2023",
    vin: "5YJ3E1EA1KF123456",
  },
  {
    id: "veh_2",
    customerId: "cus_1",
    customerName: "John Doe",
    vehicleName: "Tesla Model Y",
    model: "2024",
    vin: "5YJYGDEE2MF234567",
  },
  {
    id: "veh_3",
    customerId: "cus_2",
    customerName: "Jane Smith",
    vehicleName: "Rivian R1T",
    model: "2023",
    vin: "7FCXXXAK1PNA12345",
  },
  {
    id: "veh_4",
    customerId: "cus_3",
    customerName: "Michael Johnson",
    vehicleName: "Lucid Air",
    model: "2024",
    vin: "8AGXXXAK2PNA23456",
  },
  {
    id: "veh_5",
    customerId: "cus_3",
    customerName: "Michael Johnson",
    vehicleName: "Tesla Model S",
    model: "2022",
    vin: "5YJSA1E26MF345678",
  },
  {
    id: "veh_6",
    customerId: "cus_3",
    customerName: "Michael Johnson",
    vehicleName: "Porsche Taycan",
    model: "2023",
    vin: "WP0AA2Y18LS456789",
  },
  {
    id: "veh_7",
    customerId: "cus_4",
    customerName: "Emily Davis",
    vehicleName: "Nissan Leaf",
    model: "2023",
    vin: "1N4AZ1CP8LC567890",
  },
  {
    id: "veh_8",
    customerId: "cus_5",
    customerName: "Robert Wilson",
    vehicleName: "Chevrolet Bolt",
    model: "2024",
    vin: "1G1FY6S09P4678901",
  },
  {
    id: "veh_9",
    customerId: "cus_5",
    customerName: "Robert Wilson",
    vehicleName: "Ford Mustang Mach-E",
    model: "2023",
    vin: "3FMTK3SU8MMA78901",
  },
  {
    id: "veh_10",
    customerId: "cus_6",
    customerName: "Sarah Brown",
    vehicleName: "Hyundai Ioniq 5",
    model: "2024",
    vin: "KM8KNDAF8PU890123",
  },
  {
    id: "veh_11",
    customerId: "cus_7",
    customerName: "David Martinez",
    vehicleName: "BMW i4",
    model: "2023",
    vin: "WBA53AK09NCG01234",
  },
  {
    id: "veh_12",
    customerId: "cus_7",
    customerName: "David Martinez",
    vehicleName: "Audi e-tron",
    model: "2024",
    vin: "WA1VAAGE8PB012345",
  },
  {
    id: "veh_13",
    customerId: "cus_8",
    customerName: "Lisa Anderson",
    vehicleName: "Volkswagen ID.4",
    model: "2023",
    vin: "1V2HRER8XPC123456",
  },
  {
    id: "veh_14",
    customerId: "cus_9",
    customerName: "James Taylor",
    vehicleName: "Tesla Model X",
    model: "2024",
    vin: "5YJXCAE29MF234567",
  },
  {
    id: "veh_15",
    customerId: "cus_9",
    customerName: "James Taylor",
    vehicleName: "Polestar 2",
    model: "2023",
    vin: "LPSED4JA8PC345678",
  },
  {
    id: "veh_16",
    customerId: "cus_9",
    customerName: "James Taylor",
    vehicleName: "Mercedes EQS",
    model: "2024",
    vin: "W1KAF8DB8PA456789",
  },
  {
    id: "veh_17",
    customerId: "cus_10",
    customerName: "Jennifer Thomas",
    vehicleName: "Kia EV6",
    model: "2023",
    vin: "KNDC34LC8P7567890",
  },
  {
    id: "veh_18",
    customerId: "cus_11",
    customerName: "Christopher Lee",
    vehicleName: "Tesla Model 3",
    model: "2024",
    vin: "5YJ3E1EB2PF678901",
  },
  {
    id: "veh_19",
    customerId: "cus_11",
    customerName: "Christopher Lee",
    vehicleName: "Rivian R1S",
    model: "2024",
    vin: "7FCXXXAK5PNA78901",
  },
  {
    id: "veh_20",
    customerId: "cus_12",
    customerName: "Amanda White",
    vehicleName: "Genesis GV60",
    model: "2024",
    vin: "KMHK381BXPU890123",
  },
]

export const mockAppointments: Appointment[] = [
  {
    id: "app_1",
    customerId: "cus_2",
    customerName: "Jane Smith",
    vehicleId: "veh_3",
    vehicleName: "Rivian R1T",
    service: "Battery Inspection",
    technician: "Alex Thompson",
    startTime: new Date("2025-01-15T09:00:00"),
    endTime: new Date("2025-01-15T11:00:00"),
  status: "pending",
  },
  {
    id: "app_2",
    customerId: "cus_1",
    customerName: "John Doe",
    vehicleId: "veh_1",
    vehicleName: "Tesla Model 3",
    service: "Tire Rotation",
    technician: "Sarah Chen",
    startTime: new Date("2025-01-15T10:00:00"),
    endTime: new Date("2025-01-15T11:30:00"),
    status: "in-progress",
  },
  {
    id: "app_3",
    customerId: "cus_4",
    customerName: "Emily Davis",
    vehicleId: "veh_7",
    vehicleName: "Nissan Leaf",
    service: "Software Update",
    technician: "Mike Rodriguez",
    startTime: new Date("2025-01-15T13:00:00"),
    endTime: new Date("2025-01-15T14:00:00"),
  status: "pending",
  },
  {
    id: "app_4",
    customerId: "cus_3",
    customerName: "Michael Johnson",
    vehicleId: "veh_5",
    vehicleName: "Tesla Model S",
    service: "Brake Service",
    technician: "Alex Thompson",
    startTime: new Date("2025-01-14T14:00:00"),
    endTime: new Date("2025-01-14T16:00:00"),
    status: "completed",
  },
  {
    id: "app_5",
    customerId: "cus_6",
    customerName: "Sarah Brown",
    vehicleId: "veh_10",
    vehicleName: "Hyundai Ioniq 5",
    service: "Annual Maintenance",
    technician: "Sarah Chen",
    startTime: new Date("2025-01-16T09:00:00"),
    endTime: new Date("2025-01-16T12:00:00"),
  status: "pending",
  },
  {
    id: "app_6",
    customerId: "cus_5",
    customerName: "Robert Wilson",
    vehicleId: "veh_9",
    vehicleName: "Ford Mustang Mach-E",
    service: "Charging System Check",
    technician: "Mike Rodriguez",
    startTime: new Date("2025-01-13T10:00:00"),
    endTime: new Date("2025-01-13T11:30:00"),
    status: "cancelled",
  },
  {
    id: "app_7",
    customerId: "cus_7",
    customerName: "David Martinez",
    vehicleId: "veh_11",
    vehicleName: "BMW i4",
    service: "Diagnostic Scan",
    technician: "Alex Thompson",
    startTime: new Date("2025-01-16T14:00:00"),
    endTime: new Date("2025-01-16T15:00:00"),
  status: "pending",
  },
  {
    id: "app_8",
    customerId: "cus_8",
    customerName: "Lisa Anderson",
    vehicleId: "veh_13",
    vehicleName: "Volkswagen ID.4",
    service: "Battery Health Check",
    technician: "Sarah Chen",
    startTime: new Date("2025-01-14T09:00:00"),
    endTime: new Date("2025-01-14T10:30:00"),
    status: "completed",
  },
  {
    id: "app_9",
    customerId: "cus_9",
    customerName: "James Taylor",
    vehicleId: "veh_14",
    vehicleName: "Tesla Model X",
    service: "Suspension Repair",
    technician: "Mike Rodriguez",
    startTime: new Date("2025-01-17T10:00:00"),
    endTime: new Date("2025-01-17T13:00:00"),
  status: "pending",
  },
  {
    id: "app_10",
    customerId: "cus_10",
    customerName: "Jennifer Thomas",
    vehicleId: "veh_17",
    vehicleName: "Kia EV6",
    service: "Wheel Alignment",
    technician: "Alex Thompson",
    startTime: new Date("2025-01-15T15:00:00"),
    endTime: new Date("2025-01-15T16:30:00"),
    status: "in-progress",
  },
  {
    id: "app_11",
    customerId: "cus_11",
    customerName: "Christopher Lee",
    vehicleId: "veh_18",
    vehicleName: "Tesla Model 3",
    service: "Paint Protection",
    technician: "Sarah Chen",
    startTime: new Date("2025-01-18T09:00:00"),
    endTime: new Date("2025-01-18T11:00:00"),
  status: "pending",
  },
  {
    id: "app_12",
    customerId: "cus_12",
    customerName: "Amanda White",
    vehicleId: "veh_20",
    vehicleName: "Genesis GV60",
    service: "Climate Control Service",
    technician: "Mike Rodriguez",
    startTime: new Date("2025-01-12T13:00:00"),
    endTime: new Date("2025-01-12T14:30:00"),
    status: "completed",
  },
  {
    id: "app_13",
    customerId: "cus_13",
    customerName: "Daniel Harris",
    vehicleId: "veh_1",
    vehicleName: "Tesla Model 3",
    service: "Interior Detailing",
    technician: "Alex Thompson",
    startTime: new Date("2025-01-19T10:00:00"),
    endTime: new Date("2025-01-19T12:00:00"),
  status: "pending",
  },
  {
    id: "app_14",
    customerId: "cus_14",
    customerName: "Michelle Clark",
    vehicleId: "veh_7",
    vehicleName: "Nissan Leaf",
    service: "Windshield Replacement",
    technician: "Sarah Chen",
    startTime: new Date("2025-01-11T14:00:00"),
    endTime: new Date("2025-01-11T16:00:00"),
    status: "cancelled",
  },
  {
    id: "app_15",
    customerId: "cus_15",
    customerName: "Kevin Rodriguez",
    vehicleId: "veh_16",
    vehicleName: "Mercedes EQS",
    service: "Full Service Package",
    technician: "Mike Rodriguez",
    startTime: new Date("2025-01-20T09:00:00"),
    endTime: new Date("2025-01-20T15:00:00"),
  status: "pending",
  },
]

export const mockAutoParts: AutoPart[] = [
  {
    id: "part_1",
    name: "Brake Pad Set",
    sku: "BP-2024-001",
    quantity: 45,
    price: 129.99,
    minStock: 20,
    status: "In Stock",
  },
  {
    id: "part_2",
    name: "Air Filter",
    sku: "AF-2024-002",
    quantity: 12,
    price: 34.99,
    minStock: 15,
    status: "Low Stock",
  },
  {
    id: "part_3",
    name: "Wiper Blade Set",
    sku: "WB-2024-003",
    quantity: 67,
    price: 24.99,
    minStock: 25,
    status: "In Stock",
  },
  {
    id: "part_4",
    name: "Tire (All-Season)",
    sku: "TR-2024-004",
    quantity: 0,
    price: 189.99,
    minStock: 16,
    status: "Out of Stock",
  },
  {
    id: "part_5",
    name: "Battery Coolant",
    sku: "BC-2024-005",
    quantity: 28,
    price: 45.99,
    minStock: 10,
    status: "In Stock",
  },
  {
    id: "part_6",
    name: "Charging Cable (Type 2)",
    sku: "CC-2024-006",
    quantity: 8,
    price: 299.99,
    minStock: 10,
    status: "Low Stock",
  },
  {
    id: "part_7",
    name: "Cabin Air Filter",
    sku: "CAF-2024-007",
    quantity: 34,
    price: 29.99,
    minStock: 20,
    status: "In Stock",
  },
  {
    id: "part_8",
    name: "Windshield Washer Fluid",
    sku: "WWF-2024-008",
    quantity: 89,
    price: 8.99,
    minStock: 30,
    status: "In Stock",
  },
  {
    id: "part_9",
    name: "Brake Rotor",
    sku: "BR-2024-009",
    quantity: 3,
    price: 159.99,
    minStock: 8,
    status: "Low Stock",
  },
  {
    id: "part_10",
    name: "Suspension Spring",
    sku: "SS-2024-010",
    quantity: 16,
    price: 249.99,
    minStock: 6,
    status: "In Stock",
  },
  {
    id: "part_11",
    name: "LED Headlight Bulb",
    sku: "LH-2024-011",
    quantity: 52,
    price: 79.99,
    minStock: 15,
    status: "In Stock",
  },
  {
    id: "part_12",
    name: "Door Handle Assembly",
    sku: "DH-2024-012",
    quantity: 7,
    price: 189.99,
    minStock: 5,
    status: "In Stock",
  },
]

export const mockStaff: StaffMember[] = [
  {
    id: "staff_1",
    name: "Alex Thompson",
    email: "alex.thompson@evservice.com",
    role: "Technician",
    phone: "+1 (555) 111-2222",
    status: "Active",
  },
  {
    id: "staff_2",
    name: "Sarah Chen",
    email: "sarah.chen@evservice.com",
    role: "Technician",
    phone: "+1 (555) 222-3333",
    status: "Active",
  },
  {
    id: "staff_3",
    name: "Mike Rodriguez",
    email: "mike.rodriguez@evservice.com",
    role: "Technician",
    phone: "+1 (555) 333-4444",
    status: "Active",
  },
  {
    id: "staff_4",
    name: "Admin User",
    email: "admin@evservice.com",
    role: "Admin",
    phone: "+1 (555) 444-5555",
    status: "Active",
  },
  {
    id: "staff_5",
    name: "Jessica Martinez",
    email: "jessica.m@evservice.com",
    role: "Staff",
    phone: "+1 (555) 555-6666",
    status: "Active",
  },
  {
    id: "staff_6",
    name: "Tom Anderson",
    email: "tom.anderson@evservice.com",
    role: "Staff",
    phone: "+1 (555) 666-7777",
    status: "Active",
  },
  {
    id: "staff_7",
    name: "Rachel Kim",
    email: "rachel.kim@evservice.com",
    role: "Technician",
    phone: "+1 (555) 777-8888",
    status: "Inactive",
  },
  {
    id: "staff_8",
    name: "David Park",
    email: "david.park@evservice.com",
    role: "Staff",
    phone: "+1 (555) 888-9999",
    status: "Active",
  },
]

export const mockCertifications: Certification[] = [
  { id: "cert_1", name: "EV High-Voltage Safety", description: "Safe handling of HV systems" },
  { id: "cert_2", name: "Battery Diagnostics Pro", description: "Advanced battery diagnostics" },
  { id: "cert_3", name: "EV Powertrain Repair", description: "Motor/inverter service procedures" },
]

export const mockStaffCerts: StaffCertification[] = [
  { staffId: "staff_1", certificationId: "cert_1", obtainedDate: "2024-03-01", level: "Professional" },
  { staffId: "staff_1", certificationId: "cert_2", obtainedDate: "2024-06-12" },
  { staffId: "staff_2", certificationId: "cert_1", obtainedDate: "2023-11-20", level: "Associate" },
  { staffId: "staff_3", certificationId: "cert_3", obtainedDate: "2024-01-10", level: "Professional" },
]
